name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ec54cb6a-bec0-44d1-8351-3028708d201e
          heroku_app_name: "shreddingui"
          heroku_email: "mjmatta@bu.edu"
